# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebbc9fb05ab35fe96c42724fcc0b40bae76d64e0a10dd4e45995e4a7202d0d42f5c8f7fed69e4becc1e622b44665d07af52bf5ecf4e9da34ac440bcba325d88a

test:
  secret_key_base: ae80bc60e3d4774cf5d4b5ca8b74244e3c81367f9465c916a24ed911e1f9dfac4b36bce36392bb40dc99cbb188b06b78ae543c058e6eb22dd198a079aaf1ef17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
